import { test, expect } from "@playwright/test";

test("Library and tag review states", async ({ page }, testInfo) => {
  const errors = [];
  page.on("pageerror", error => errors.push(String(error)));
  page.on("console", message => { if (message.type() === "error") errors.push(message.text()); });
  await page.clock.setFixedTime(new Date("2026-01-01T00:00:00Z"));
  await page.goto("/tests/ui/");
  const library = page.locator(".library");
  await expect(library.locator("li.row")).toHaveCount(6);
  await expect(library.locator(".tag-summary")).toHaveCount(5);
  await expect(library.locator(".tag-summary button")).toHaveCount(0);
  const toggle = library.getByRole("button", { name: /^Tags/ });
  await expect(toggle).toHaveAttribute("aria-expanded", "false");
  await expect(library.getByLabel("Match selected tags", { exact: true })).toHaveCount(0);
  await page.evaluate(() => document.fonts.ready);

  async function capture(name) {
    await page.mouse.move(0, 0);
    await page.evaluate(() => window.scrollTo(0, 0));
    const path = testInfo.outputPath(`${testInfo.project.name}-${name}.jpg`);
    await page.screenshot({ path, quality: 70, fullPage: true, animations: "disabled", caret: "hide" });
    await testInfo.attach(name, { path, contentType: "image/jpeg" });
  }
  await capture("library");
  await toggle.click();
  await library.getByLabel("Tag candidate", { exact: true }).selectOption("genre:funkot");
  await library.getByRole("button", { name: "Add condition", exact: true }).click();
  await expect(library.locator("li.row")).toHaveCount(5);
  await capture("tag-filter");
  await toggle.click();
  await expect(toggle).toHaveText("Tags (1)");
  await expect(library.getByLabel("Tag candidate", { exact: true })).toHaveCount(0);
  await expect(library.locator("li.row")).toHaveCount(5);
  await toggle.click();
  // Exercise combined predicates and removal through the single toolbar entry.
  await library.getByLabel("Production year unset", { exact: true }).check();
  await expect(library.locator("li.row")).toHaveCount(3);
  await library.getByLabel("Tag candidate", { exact: true }).selectOption("year:2024");
  await library.getByRole("button", { name: "Add condition", exact: true }).click();
  await expect(library.locator("li.row")).toHaveCount(0);
  await library.getByLabel("Match selected tags", { exact: true }).selectOption("any");
  await expect(library.locator("li.row")).toHaveCount(3);
  await library.getByRole("button", { name: "Remove condition Production year: 2024", exact: true }).click();
  await library.getByRole("button", { name: "Remove condition Genre: Funkot", exact: true }).click();
  await expect(library.locator("li.row")).toHaveCount(4);
  await library.getByRole("button", { name: "Clear tag conditions", exact: true }).click();
  await toggle.click();
  await library.locator("li.row").filter({ hasText: "Midnight on the coast" }).click({ button: "right" });
  await page.getByRole("menuitem", { name: "Edit tags", exact: true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await capture("tag-editor");
  const dialog = page.getByRole("dialog");
  await expect(dialog.getByRole("button", { name: "Save", exact: true })).toBeInViewport();
  await expect(dialog.getByRole("button", { name: "〔Cancel〕", exact: true })).toBeInViewport();
  await dialog.getByRole("button", { name: "Remove Genre: Funkot", exact: true }).click();
  await expect(dialog.getByRole("button", { name: "Undo: Genre: Funkot", exact: true })).toHaveAttribute("aria-pressed", "true");
  await dialog.getByRole("button", { name: "Undo: Genre: Funkot", exact: true }).click();
  await dialog.getByLabel("Tag", { exact: true }).fill("Warm up");
  await page.keyboard.press("Enter");
  await expect(dialog.getByRole("button", { name: "Undo: Genre: Warm up", exact: true })).toBeVisible();
  await dialog.getByRole("button", { name: "Undo: Genre: Warm up", exact: true }).click();
  await dialog.getByLabel("Production year", { exact: true }).selectOption("set");
  await dialog.getByRole("button", { name: "Save", exact: true }).click();
  await expect(dialog.getByRole("alert")).toHaveText("Check the tag value.");
  await expect(dialog.getByRole("alert")).toBeInViewport();
  await dialog.getByLabel("Set year", { exact: true }).fill("2025");
  await dialog.getByLabel("Production year", { exact: true }).selectOption("auto");
  await dialog.getByLabel("Production year", { exact: true }).selectOption("unset");
  await dialog.getByLabel("Production year", { exact: true }).selectOption("unchanged");
  // Exercise warnings through the existing store seam; no persistence is mocked.
  await page.evaluate(async () => {
    const { store } = await import("/src/lib/state.svelte.ts");
    store.trackTags = { ...store.trackTags, revision: "changed-elsewhere", store_status: "invalid" };
  });
  await expect(dialog.getByRole("alert", { name: "" }).filter({ hasText: "read-only" })).toBeVisible();
  await expect(dialog.getByRole("button", { name: "Save", exact: true })).toBeDisabled();
  await expect(dialog.getByText("Tags changed elsewhere", { exact: true })).toBeVisible();
  await dialog.getByRole("button", { name: "Reload tags", exact: true }).click();
  await expect(dialog.getByText("Tags reloaded", { exact: true })).toBeVisible();
  await expect(dialog.getByRole("button", { name: "Save", exact: true })).toBeEnabled();
  await dialog.locator("summary").click();
  await expect(dialog.getByRole("button", { name: "Save", exact: true })).toBeInViewport();
  await dialog.getByRole("button", { name: "Save", exact: true }).focus();
  await page.keyboard.press("Tab");
  await expect(dialog.getByLabel("Production year", { exact: true })).toBeFocused();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await expect(library.locator("li.row").filter({ hasText: "Midnight on the coast" })).toBeFocused();
  await library.getByRole("button", { name: "Select several tracks", exact: true }).click();
  await library.getByRole("checkbox", { name: "Select Pulse", exact: true }).check();
  await library.getByRole("checkbox", { name: "Select Dawn", exact: true }).check();
  await library.getByRole("button", { name: "Edit visible selected (2)", exact: true }).click();
  await expect(dialog.getByText("2 displayed selected tracks", { exact: true })).toBeVisible();
  await expect(dialog.getByLabel("Production year", { exact: true })).toHaveValue("unchanged");
  await expect(dialog.getByRole("button", { name: "Save", exact: true })).toBeInViewport();
  await page.keyboard.press("Escape");
  expect(errors).toEqual([]);
});
