#!/bin/sh
# Check the invariants that only break in an Android *release* build.
#
# `isMinifyEnabled` is false for debug and true for release, so anything R8
# shrinks away is invisible to every on-device check made with a debug APK, and
# there is no build warning either. The result is a release-only
# NoSuchMethodError -- which is exactly how `Import.hasInFlight` shipped broken,
# taking share-sheet import with it for as long as the feature existed.
#
# Run this before building a release APK: that build happens locally and never
# passes through CI. CI runs it on every push (.github/workflows/checks.yml).
# It needs nothing but a POSIX shell -- no Docker, no toolchain -- which is what
# makes it cheap enough to run every time. Keep it that way.
#
# POLICY: when a bug turns out to be of the "debug passes, release is silently
# broken" kind, do not just fix it -- add a check here that would have caught
# it. A rule that lives only in a code comment gets skipped by the next person
# who adds a class; one that lives here cannot be. New checks go in as a
# `check_*` function, called from the list at the bottom.
set -eu

cd "$(dirname "$0")/.."

LIB=src-tauri/src/lib.rs
PRO=src-tauri/gen/android/app/proguard-rules.pro

# proguard-tauri.pro is deliberately not read: it is autogenerated, marked DO
# NOT EDIT, and keeps TauriActivity, which Rust never names over JNI.

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT INT TERM

status=0

# Every app class Rust loads by name over JNI needs a `-keep ... { *; }` line.
#
# `load_class` and `call_static_method` take the class and the method as
# *strings*, so R8 sees no reference to either and is free to shrink or rename
# them. `{ *; }` is required rather than the class alone: keeping the class
# while its members are renamed fails in exactly the same way, so a bare
# `-keep class ...` line does not count and is reported as missing.
check_jni_keep_rules() {
    grep -o 'jni_str!("jp\.hatsuboshi\.funkotplayer\.[A-Za-z0-9_]*")' "$LIB" \
        | sed 's/^jni_str!("//; s/")$//' | sort -u > "$TMP/rust"
    grep -oE '^-keep class jp\.hatsuboshi\.funkotplayer\.[A-Za-z0-9_]+ *\{ *\*; *\}' "$PRO" \
        | sed -E 's/^-keep class //; s/ *\{ *\*; *\}$//' | sort -u > "$TMP/proguard"

    if diff "$TMP/rust" "$TMP/proguard"; then
        return 0
    fi
    echo "FAIL: JNI class names and R8 keep rules disagree." >&2
    echo "  '<' only in $LIB -- add '-keep class <name> { *; }' to $PRO" >&2
    echo "  '>' only in $PRO -- stale or misspelled keep rule; remove or fix it" >&2
    return 1
}

# Every `load_class` call must name its class with a literal the check above can
# see. A name built at run time -- a const, a variable, format! -- would leave
# that check passing while covering nothing. If an app-external class is ever
# loaded this way on purpose, widen this check. Do not delete it.
check_load_class_literals() {
    calls=$(grep -o 'load_class(' "$LIB" | wc -l | tr -d ' ')
    literals=$(grep -o 'jni_str!("jp\.hatsuboshi\.funkotplayer\.[A-Za-z0-9_]*")' "$LIB" \
        | wc -l | tr -d ' ')
    [ "$calls" = "$literals" ] && return 0
    echo "FAIL: $LIB has $calls load_class call(s) but $literals literal app-class name(s)." >&2
    echo "  A class name that is not a literal is invisible to the keep-rule check." >&2
    return 1
}

check_jni_keep_rules      || status=1
check_load_class_literals || status=1

if [ "$status" = 0 ]; then
    echo "release-only invariants: OK"
fi
exit "$status"
